snapshot-labs/snapshot-sequencer

src/writer/delete-proposal.ts
Depend on https://github.com/snapshot-labs/snapshot.js/pull/779
=> feat: allow moderators to archive proposals

src/writer/delete-proposal.ts, src/writer/proposal.ts
This PR allows admins and moderators to post a proposal regardless of their voting power.
=> feat: authorize admins and mods to post proposals

src/index.ts
`3000` port is conflicting with hub, so changed it to `3001`
=> Change default port

src/scores.ts
Works only with https://github.com/snapshot-labs/snapshot.js/pull/791
=> Calculate votes count and scores even if shutter is enabled

src/writer/proposal.ts
Related to https://github.com/snapshot-labs/snapshot/issues/3466
=> Use voting validations for proposals

src/helpers/actions.ts, src/helpers/schema.sql, src/helpers/utils.ts, src/writer/delete-space.ts, src/writer/index.ts, src/writer/settings.ts
Closes https://github.com/snapshot-labs/snapshot-hub/issues/563
**Important**
Admin task:
```SQL
ALTER TABLE
`spaces`
ADD
COLUMN `deleted` INT NOT NULL DEFAULT 0 After verified;
```
=> Delete space action

src/helpers/shutter.ts
Noticed we are not using these functions anywhere else
=> Chore: remove unused exports

src/ingestor.ts
=> feat(ipfs body): add EIP712 hash to ipfs body

src/helpers/actions.ts, src/ingestor.ts, src/writer/index.ts, src/writer/statement.ts
This PR add statement action with a new table "statements".
=> feat: add statement action

src/helpers/limits.ts, src/helpers/moderation.ts, src/writer/proposal.ts
Adding new limit for daily and monthly proposal created for flagged and unverified spaces.
=> feat: add custom limit for flagged and unverified spaces

src/helpers/moderation.ts, src/ingestor.ts
There is a hardcoded list of spam IPs
Remove this hardcoded list, and pull them from laser mysql database
Fix #81 
- Remove the hardcoded IP list
- Get list from sidekick moderation list
- Impossible to test ... Trust the code
=> feat: pull flagged IPs list from sidekick

package.json, src/api.ts, src/helpers/ens.ts, src/helpers/moderation.ts, src/helpers/sentry.ts, src/helpers/shutter.ts, src/helpers/utils.ts, src/index.ts, src/ingestor.ts, src/scores.ts, src/writer/delete-space.ts, src/writer/profile.ts, src/writer/proposal.ts, src/writer/settings.ts, src/writer/statement.ts, src/writer/vote.ts, yarn.lock
- Setup project to send errors to Sentry
- Send all caught errors to sentry (basically, call `capture(e)` each time there is a `catch (e)`
=> chore: add sentry

.github/workflows/lint.yml, package.json, yarn.lock
This PR is part of DX improvement
- Add lint task to CI
=> chore: add lint to CI

src/helpers/actions.ts, src/ingestor.ts, src/writer/delete-proposal.ts
Fix #119 
Fix SNAPSHOT-SEQUENCER-C
Fix an error when trying to process a proposal which does not exist
=> fix: reject transaction when proposal does not exist

.env.example, package.json, src/helpers/rateLimit.ts, src/helpers/utils.ts, yarn.lock
- Add `RATE_LIMIT_DATABASE_URL` env
=> Redis store to rate limit

src/helpers/metrics.ts
This PR add metrics to track the number of open connections on expressjs server
=> chore: instrument express open connections count

package.json, src/helpers/metrics.ts, yarn.lock
- Update snapshot-metrics to latest version (add pushgateway support)
=> chore: upgrade metrics to 1.1.0

src/helpers/metrics.ts
This PR instrument the failing ingestor process, logging which the error message, as well as the response time.
This instrumentation will give us metrics about how long has passed before the request is failing, with the given error.
Those metrics will let us optimize the code, to fail as earlier as possible
=> fix: instrument failed ingestor process

src/helpers/moderation.ts, src/helpers/rateLimit.ts, src/helpers/shutter.ts, src/writer/delete-space.ts, src/writer/settings.ts, src/writer/vote.ts
- Remove redundant `console.log`
- Move the last few `log.error` to `log.warn`
=> chore: make logging consistent

src/ingestor.ts, src/writer/alias.ts
payload was missing in my previous commit, which is causing the issue
=> fix: Alias payload is missing

src/helpers/moderation.ts, test/integration/helpers/moderation.test.ts, test/integration/ingestor.test.ts, test/unit/writer/proposal.test.ts
Fix test hanging, due to async functions not returning properly
=> chore: fix test open handles

src/helpers/limits.ts, src/writer/follow.ts, test/integration/writer/follows.test.ts
Fixes https://github.com/snapshot-labs/snapshot/issues/4286
We now limit users to have the follows of 50 spaces. They won't be able to follow more spaces than that
=> feat: Add limit for follows per user

src/writer/proposal.ts, test/integration/ingestor.test.ts, test/unit/writer/proposal.test.ts
Fix #214 
Enforce proposal `end` property to be in the future
=> fix: enforce proposal `end` date to be in the future

test/integration/writer/follows.test.ts
Fix tests broken by https://github.com/snapshot-labs/snapshot-sequencer/commit/39a2733ade48a96bedc2c7882fd059be797f7b8d
=> fix: fix tests

src/helpers/log.ts
=> chore: silence logs on test env

src/writer/settings.ts
Do not validation space settings on proposal creation
=> fix: disable settings  validation on space creation

src/writer/settings.ts
This reverts commit 0edaad1386ba7410bab79c057725904d8055138d.
=> Revert "fix: disable settings  validation on space creation (#244)"

src/writer/proposal.ts
Related to pitch https://github.com/orgs/snapshot-labs/projects/12/views/7?pane=issue&itemId=43161232
Add a validation, and reject on proposal creation, when the space is hibernated
=> fix: prevent hibernated spaces from creating proposals

src/helpers/shutter.ts
we already have a log at https://github.com/snapshot-labs/snapshot-sequencer/blob/remove-unused-logs/src/helpers/shutter.ts#L94 so this is just removing duplicate one
=> chore: Remove duplicate log

jest.config.ts, test/integration/helpers/poke.test.ts
Auto merging of https://github.com/snapshot-labs/snapshot-sequencer/commit/d7093c0fd4fdd70e768138f02125dd43c25ed5c4 has been botched due to too old PR compared to master.
This PR fix the tests files
=> fix: fix wrongly merged files

src/helpers/moderation.ts
=> fix: Proposal unflag is not working

src/helpers/moderation.ts, test/integration/helpers/moderation.test.ts, test/integration/ingestor.test.ts
Some dead code in moderation.ts
Remove dead code
- Remove dead code in moderation for proposals body and title keywords, which are not used for moderation anymore
- Improve the moderation API links to fetch only the needed list
- N/A
=> fix: remove dead moderation code

src/helpers/metrics.ts, src/writer/proposal.ts
We have no insight about the number of proposals filtered out by blockaid
Instrument the number of proposals blocked by blockaid
- Add counter to record number of proposals blocked by blockaid
=> feat: Instrument blockaid requests

src/writer/delete-proposal.ts
This doesn't work because of #127 
Will be fixed in the future
=> fix: Delete proposal doesn't work

src/writer/vote.ts
remove the leaderboard query, debugging if it's the cause the sql `ER_LOCK_DEADLOCK` errors
=> fix: fix ER_LOCK_DEADLOCK error when inserting votes

src/writer/vote.ts
Reverts snapshot-labs/snapshot-sequencer#334
=> Revert "fix: fix ER_LOCK_DEADLOCK error when inserting votes"

src/helpers/limits.ts, test/unit/writer/proposal.test.ts
Context: https://discord.com/channels/955773041898573854/1125390177888645231/1234850610612797451
We now need ecosystem limits for testnet spaces
- Change your local .env to use `NETWORK=testnet`
- Add a log here https://github.com/snapshot-labs/snapshot-sequencer/blob/master/src/writer/proposal.ts#L184
- Try creating a proposal with testnet ecosystem space
=> fix: Add testnet ecosystem spaces

src/helpers/alias.ts
- Use alias that were created  within last 30 days 
How to test:
- Try following a space with a alias that was created 30 days ago
TODO:
=> fix: Only use aliases that were created within the last 30 days

src/writer/delete-proposal.ts, src/writer/delete-space.ts, src/writer/proposal.ts, src/writer/vote.ts
Context: https://discord.com/channels/955773041898573854/1031838169282392144/1242062206883856414
=> fix: Disable leaderboard updates

test/integration/writer/proposal.test.ts
=> chore: fix tests

test/schema.sql
Schema update to match the new column length for space in follows table
=> fix: update sql schema for new space length in follows table

src/ingestor.ts
Fix new Statement properties missing from the payload
=> fix: fix new statement properties being ignored

src/ingestor.ts
This PR enable alias for `Statement` update globally
=> fix: enable alias for statement

src/writer/statement.ts, test/schema.sql
Uppercase statement status
- Merge after https://github.com/snapshot-labs/snapshot.js/pull/1026
- Update database manually to uppercase all existing data
=> fix: uppercase statement status

scripts/refresh-space-leaderboard.ts
- Make `space` input optional
- Add `start` and `end` inputs
- `yarn ts-node scripts/refresh-space-leaderboard.ts`
=> Refresh leaderboard for all spaces

src/writer/profile.ts
Following https://github.com/snapshot-labs/stamp/pull/262 
This PR will call the stamp clear address cache when a user's name has been edited
=> feat: clear stamp address cache on user profile name update

src/helpers/utils.ts
Context: https://discord.com/channels/955773041898573854/1182427601046884352/1265683958558097459
=> Add rocketpool-node-operator-delegate-v8 to override list

src/ingestor.ts, test/integration/ingestor.test.ts
This reverts commit d6a74329b386333bb37e763915f67e076f8bf525.
=> Revert "fix: validate space ID (#417)"

src/helpers/limits.ts
Context: 
https://discord.com/channels/955773041898573854/1103266859870081114/1276396777603334248
It should not be possible to create proposals on flagged spaces
=> fix: Reduce proposal limit for flagged spaces

src/helpers/schema.sql, test/schema.sql
Context https://discord.com/channels/955773041898573854/1030772407226601522/1286013658438307953
```sql
ALTER TABLE
messages
MODIFY
sig varchar(3000) NOT NULL;
```
=> fix: Update sig field length

src/writer/settings.ts
Towards https://github.com/snapshot-labs/workflow/issues/143
- Check for unique label IDs and names
- Use https://github.com/snapshot-labs/sx-monorepo/pull/829 and change to localhost hub and sequencer
- Disable check with `checkLabelExists` https://github.com/snapshot-labs/sx-monorepo/blob/a7344ff904f33456a9cf0a781cf8f43dce4c17c1/apps/ui/src/components/FormSpaceLabelsList.vue#L30-L32
- Add duplicate labels
=> feat: Check for unique label IDs and names

src/helpers/utils.ts
Related to https://github.com/snapshot-labs/sx-monorepo/pull/868
=> feat: support custom choices for basic voting

src/helpers/actions.ts, test/integration/helpers/actions.test.ts
as suggested https://github.com/snapshot-labs/snapshot-sequencer/pull/459#discussion_r1802752060
=> refactor: delegationNetwork default value

src/ingestor.ts
Same as https://github.com/snapshot-labs/snapshot-sequencer/pull/479
=> fix: Increase timestamp check to 6 days

src/helpers/actions.ts, test/integration/helpers/actions.test.ts
With this change we will use unified API to get space info.
I tested that `sxSpaceExists` tests pass.
=> feat: use unified API to check if SX space exists

src/helpers/utils.ts
Updated mantle to mnt as it's new NetworkID for it.
=> feat: add mnt, ape, curtis to networks whitelist

src/helpers/utils.ts, src/writer/delete-space.ts, src/writer/settings.ts
Toward https://github.com/snapshot-labs/workflow/issues/523
Continuation of https://github.com/snapshot-labs/snapshot.js/pull/1138 to use the correct network for space id using .shib names
=> feat: use correct network when fetching shib space controller

src/helpers/utils.ts
Related to https://github.com/snapshot-labs/workflow/issues/626
=> chore: add sonic-staked-balance to override strategy

src/helpers/mysql.ts
=> chore: enable SSL with rejectUnauthorized

src/scores.ts
Fix https://snapshot-labs.sentry.io/issues/6854066828/?project=4505606761152512&query=is%3Aunresolved&referrer=issue-stream
This PR fix the missing conversion from string to array type
=> fix: fix missing conversion from string to array

src/writer/proposal.ts
Fix https://snapshot-labs.sentry.io/issues/5998908581/?project=4505606761152512&query=is%3Aunresolved&referrer=issue-stream
Fix wrong function name
=> fix: fix invalid logger name

src/ingestor.ts
right now json stringify hiding the entire error
=> chore: improve signature validation logging
