src/writer/settings.ts
Part of https://github.com/snapshot-labs/snapshot/issues/3472
---------------
**!IMPORTANT:**  So one thing to note is if the `snapshot` text record is IPFS or URL, we still allow new settings from the ENS controller, I think it should be fine
---------------
TODO:
=>  Allow ENS controller to be snapshot space controller

src/writer/proposal.ts
An empty string in score_state is causing confusion, refer to https://github.com/snapshot-labs/snapshot/issues/3555#issuecomment-1457769239
so made it `pending`
=> Default score_state to pending instead of empty string

src/writer/vote.ts
Related to https://github.com/snapshot-labs/snapshot/pull/4053
Right now if we are not using custom strategies in basic validation, it fails, we should fallback to proposal strategies instead
How to test:
- Change your space settings to use basic validation and don't use any custom strategies
- Try to create a proposal and vote on it
- It will fail earlier, it should pass through with these changes
=> Use proposal strategies if basic validation doesn't have strategies

src/helpers/utils.ts
This is for voting power calculation issue of a proposal, will revert soon
=> Add moonbeam-free-balance to override strategies to avoid outdated VP on existing votes

package.json
The current production app is run directly on typescript file with `ts-node`, instead of `node` on compiled js files.
This result in up to 10x more memory consumption.
- Run app on compiled js files
- Build js files
- Run app on js files
- Run `yarn build`
- Run `yarn start`
- It should start the app
=> chore: run prod app with node instead of ts-node

src/writer/proposal.ts
Add exception for members of a space (author, moderator or admin) to active proposal limit
=> fix: allow space members to skip active proposal limit

src/helpers/limits.ts
Reducing limit back after adding exception for space members https://github.com/snapshot-labs/snapshot-sequencer/pull/97
=> fix: decrease active proposal limit for non-members

src/helpers/limits.ts
Temporary fix to allow a slightly higher daily proposal limit for ecosystem spaces. To be reverted soon.
=> hotfix: temporarily increase ecosystem daily proposal limit

src/helpers/moderation.ts, src/writer/proposal.ts
There's a few hardcoded list of flagged items:
https://github.com/snapshot-labs/snapshot-sequencer/blob/13dc5b314b69ff4829e67ab6815ef537cdf1374e/src/writer/proposal.ts#L93-L99
These items have already been migrated to laser/sidekick, and can already been pulled from sidekick
- Fetch the list from sidekick
=> fix: pull flagged items from laser database

package.json, yarn.lock
Previous beta version of shutter was conflicting with Sentry package, and crashes.
See https://github.com/shutter-network/rolling-shutter/issues/390
The issue has now been fixed from shutter side, and they released a new stable 1.0.0 version.
=> chore: upgrade shutter dependency to latest stable

.github/workflows/create-sentry-release.yml
The workflow was set to run on `main` instead of `master`
=> chore: fix wrong branch name in workflow

.github/workflows/create-sentry-release.yml, src/api.ts, src/ingestor.ts, src/writer/profile.ts, src/writer/proposal.ts, src/writer/settings.ts, src/writer/statement.ts, src/writer/vote.ts
The initial sentry installation commit was only putting a `capture()` in all catch blocks.
After monitoring the errors, there's a few cases where a try/catch is being used to catch invalid user input. 
This PR is removing a few `capture()` calls, which were logging user invalid input as errors, which should be filtered out as they're not code related errors.
=> chore: do not send user input errors to Sentry

.github/dependabot.yml
Relax dependabot rules to include all package from @snapshot-labs (to also include pineapple, config, metrics, and sentry)
=> chore: allow update notification for all package from organization

package.json, src/api.ts, src/helpers/ens.ts, src/helpers/utils.ts, src/ingestor.ts, src/writer/delete-space.ts, src/writer/proposal.ts, src/writer/settings.ts, src/writer/vote.ts, test/e2e/api.test.ts, tsconfig.json, yarn.lock
Currently, `Promise.reject` are used for client error, and `throw` for server error. They're caught later up in the code, near the express router with a `try/catch`.
Current issue is that try/catch does not differentiate between user and server error, creating a lot of noise on Sentry
Fix #124
Inside the `catch` block, let's assume that when the argument is a `string`, it's `Promise.reject` due to client error and ignored from Sentry, and if it's an `Error` object, it's a server error and let's log it to Sentry.
This PR purpose is to filter out noise, so we can re-enable Sentry on this service
- Before sending errors to Sentry, filter and only send true errors, ignoring all Promise rejection.
- When failing due to client error, return a `400` error code. 
- Fix the `capture` function …
=> chore(refactor): filter out client error from Sentry

src/helpers/metrics.ts
This PR add metrics to track the count of rate limited requests
This is a copy/paste of the same code already on hub and score-api
=> chore: instrument rate limited request

src/helpers/ens.ts, src/writer/delete-space.ts, src/writer/proposal.ts, src/writer/settings.ts
This PR updates the `capture` call to use the shorter signature, added in  https://github.com/snapshot-labs/snapshot-sentry/releases/tag/v1.3.0
=> chore: update capture signature

jest.config.ts, package.json, test/integration/ingestor.test.ts, yarn.lock
This PR update pineapple.js to v1, which enable kepp alive connections
=> fix: update to pineapple@1

src/helpers/metrics.ts
This PR exclude 429 errors from instrumented errors in the ingestor workflow.
429 errors are skewing the results, and creating a lot of noise
=> fix: ignore 429 from ingestor process error instrumentation

.github/workflows/create-sentry-release.yml
Customize the sourcemaps location when uploading to Sentry
=> chore: customize the sourcemaps location path

package.json, yarn.lock
This PR upgrade pineapple.js to 1.1.0, which is adding support for retry on 504 errors
=> chore: upgrade to pineapple  to 1.1.0

src/helpers/moderation.ts
Changed the flow of flagging/verifying spaces:
- if space marked `verified=1` then the `flagged=0`
- if space marked `flagged=1` then the `verified=0`
=> feat(flag): trigger verified/flagged field on set opposite data

src/helpers/moderation.ts, test/integration/helpers/moderation.test.ts
The retrieving of the moderation list from sidekick is done through the `getJSON` utils from snapshot.js.
While this is convenient, it complicates the error handling and tracking.
Move the JSON fetching to a full-fledged `fetch` function call.
This allow rescuing, handling, and tracking of different kind of errors. This will also allow use of keep-alive, timeout and retry connections in a future PR.
- Migrate from `getJSON` to `fetch` to retrieve moderation data
- Handle error when fetching JSON data is failing
- Add tests
- Trust the tests
=> fix: use `fetch` to load remote JSON data

package.json, src/helpers/actions.ts, src/helpers/limits.ts, src/helpers/moderation.ts, src/writer/proposal.ts, test/fixtures/space.ts, test/integration/helpers/actions.test.ts, test/integration/helpers/highlight.test.ts, test/integration/helpers/moderation.test.ts, test/integration/ingestor.test.ts, test/schema.sql, test/unit/writer/proposal.test.ts
The rateLimit module is still using flagged and verified spaces from sidekick, which is now obsolete
Use flagged and verified spaces from hub directly
- Change the rateLimit code to fetch space's `verified` and `flagged` status directly from the space object 
- the `getSpaceLimits` function inside helpers/limit.ts now take a Space object, instead of spaceId
- When using `getSpace()`, check after that space is set before using
- Tests have been added
=> fix: use moderation data from hub

src/helpers/highlight.ts, test/integration/helpers/highlight.test.ts, test/integration/ingestor.test.ts
Related to https://www.notion.so/snapshotlabs/Move-all-messages-to-sequencer-f7843f0b1f3049b79f87647ca652d181
To use only sequencer DB instead of both hub and sequencer DB like before
=> feat: Use only sequencer DB for messages

package.json, test/e2e/api.test.ts, yarn.lock
- Auto-run `yarn test:setup` before `yarn:test`
- Remove unused `cross-fetch` dependencies
- Remove `supertest` dependency, replace by simpler `node-fetch`
=> chore: setup db on test run

src/helpers/rateLimit.ts
Stop logging errors for rate limiting.
This is polluting the logs, and those requests are already tracked via the dashboard
=> chore: stop logging 429 errors

src/writer/proposal.ts, test/unit/writer/proposal.test.ts
There are no check on the proposal's `snapshot` minimum value. People can submit very small block number not indexed by the nodes, resulting in error while computing voting power and scores.
Fix #224 
We should check that the snapshot value is in the range of the chosen network, by ensuring that `snapshot` is always equal or greater than the `start` property in networks.json
- Check that `snapshot` >= network's `start` block
- Submit a proposal with a very small snapshot, it should fail with a `proposal snapshot must be after network start` error
=> fix: ensure snapshot value is in the network range

package.json, src/ingestor.ts, yarn.lock
More details here: https://github.com/snapshot-labs/snapshot.js/pull/927
=> Fix: Rename types.json to hashedTypes.json

src/helpers/actions.ts, test/fixtures/space.ts, test/schema.sql
Ref to https://github.com/snapshot-labs/snapshot-hub/pull/740
Rename the Space's `created_at` and `updated_at` properties to just `created` and `updated`, for consistency
=> fix: rename `_at` suffix from Space timestamp properties

src/helpers/moderation.ts
From pitch https://github.com/orgs/snapshot-labs/projects/12/views/7?pane=issue&itemId=43161232
Add support for `hibernate` and `reactivate` on the `/flag` endpoint (so that discord bot cna hibernate and reactivate spaces https://github.com/snapshot-labs/laser/pull/22)
=> feat: add `hibernate` and `reactivate` actions to moderation

src/api.ts, src/helpers/metrics.ts, src/helpers/requestDeduplicator.ts
Triggering GET `scores/PROPOSAL-ID` may be costly, and should be done only once when asked multiple time simultaneously.
Fix https://github.com/snapshot-labs/snapshot/issues/4485
Install requestDeduplicator (same function as in other repo), to ensure we do not trigger multiple parallel request on the same proposal ID
- Add requestDeduplicator helper (+ track metrics)
- serve the `/scores/PROPOSAL-ID` endpoint through the requestDeduplicator
=> feat: add requestDeduplicator to updateProposalAndVotes

package.json, src/writer/proposal.ts, src/writer/settings.ts, src/writer/update-proposal.ts, test/unit/writer/settings.test.ts, yarn.lock
Change proposal body limit and strategies limit based on space type
- Use UI from https://github.com/snapshot-labs/snapshot/pull/4495/
- Add 10 strategies in space settings for turbo spaces
- Add 8 strategies in space settings for normal spaces
- Proposal body with 20000 characters for turbo spaces
- Proposal body with 10000 characters for normal spaces 
- Update proposal with different chars length
=> feat: Change proposal body limit and strategies limit for turbo spaces

package.json
Relax nodejs version to allow node 18.
Test have been run on node 18, and pass
=> fix: relax node version to allow node 18

src/scores.ts, src/writer/update-proposal.ts
When updating a proposal with new choices, and when the `scores` and `scores_by_strategy` properties have been updated with empty values (eg. `[[0]]` instead of default `[]`), these fields are not updated, causing them to not have same number of element as the new choices element.
This cause errors on the UI side, which expect a `score` for each `choice`.
Fix #276 
- On proposal update, reset the `scores` and `scores_by_strategy` to an empty array. This reset does not cause side effect, as pending proposals does not have any scores yet.
- Also disable any `scores` and `scores_by_strategy` update when proposal is pending
=> fix: fix invalid scores array length after choices update

src/helpers/moderation.ts, src/writer/proposal.ts, src/writer/update-proposal.ts, test/integration/helpers/moderation.test.ts, test/integration/writer/proposal.test.ts
Proposals with flaggedLinks and proposals flagged manually are handled differently.
Auto-flag proposals containing flagged links, so the the only source of truth for flagging is the `flagged` column in the proposals table
- Load `flaggedLinks` data from moderation endpoint
- When creating and updating proposals, flag proposal when the body contains flagged links
- create some proposals with body containing flagged links
- the proposal should be flagged, without manual moderation
=> fix: auto flag proposal when the body contains flagged links

src/writer/proposal.ts
We got some errors due to connection issues with brovider
Fix #286
Fix [SNAPSHOT-SEQUENCER-2V](https://snapshot-labs.sentry.io/issues/4912710121/?referrer=github_integration)
Handle errors for remaining direct calls to brovider
- Add a try/catch when calling brovider
=> fix: handle error when unable to get current block

package.json, src/helpers/rateLimit.ts, yarn.lock
On redis connection issues, rate-limit middleware is blocking the whole request workflow, and not letting through any requests.
Fix #289 
On redis connection issues, rate-limit middleware should be ignored, and all requests should bypass the middleware.
- Bypass rate-limit middleware when redis is not ready
- Update `rate-limit-redis` package to 3.1.0, to support redis reconnection, else will throw https://github.com/express-rate-limit/rate-limit-redis/issues/144
- Start your redis server
- yarn dev
- Send some requests to localhost:3001
- It should returns headers like `Ratelimit-Limit`
- Stop the redis server
- It should start logging connections error on the `yarn dev` console
- Send some requests to localhost:3001
- It should return results as usual
- The headers `Ratelimit-Limit` …
=> fix: ignore redis error on rate limit

package.json
The `test` command may be stuck while using `start-server-and-test`, due to it listening on `127.0.0.1` instead of `localhost`. On some env, those 2 urls are the same, but not always (see https://www.npmjs.com/package/start-server-and-test#localhost-vs-0000-vs-127001)
`yarn dev` is starting on `localhost`, so `start-server-and-test` should also be explicitly told to listen on `localhost`
- Update `test` command to listen on the full url instead of just the port
- Run `yarn test`
- It should run the test
=> chore: fix `test` command stuck waiting on wrong url 

src/ingestor.ts
In logs i find logs like this:
```
New "alias" on "undefined",  for "0xF5b32cd4Fda955B099d8436e30e...
```
This is confusing, so adding `spaceText` only when space is available
=> fix: undefined logs on alias action

src/writer/proposal.ts, test/schema.sql
Related to https://github.com/snapshot-labs/snapshot/issues/4600
```
ALTER TABLE proposals
ADD COLUMN quorum_type VARCHAR(24) DEFAULT '' AFTER quorum;
```
- Add `quorumType` on space settings
- On proposal creation, we should be able to store `quorumType` on proposals table
=> fix: Store quorum type on proposal

src/writer/proposal.ts, test/unit/writer/proposal.test.ts
Fixes https://github.com/snapshot-labs/snapshot-sequencer/issues/309
- Will check if `snapshot` block exists on the particular network
- Previously we were checking `snapshot` with the current block
- Go to your proposal creation page, for example https://snapshot.org/#/thanku.eth/create?snapshot=true
- Try creating proposal with future `snapshot`
- <img width="635" alt="Untitled 2" src="https://github.com/snapshot-labs/snapshot-sequencer/assets/15967809/1f03b28e-f7e1-46e7-91cc-c50e715fba9b">
- Before: it should throw error `proposal snapshot must be in past`
- Now: it should throw error `invalid snapshot block`
=> Fix: On proposal creation check if snapshot block exist

src/helpers/monitoring/blockaid.ts, src/helpers/monitoring/chainpatrol.ts, src/helpers/shutter.ts
Some fetch requests are not using `keepAlive`, such as shutter decryption or chain patrol monitoring.
These requests benefit from `keepAlive`, as they're sending multiple requests at the same time, and will fix the `EAI_AGAIN` network error
Closes #326 
Closes [SNAPSHOT-SEQUENCER-26](https://snapshot-labs.sentry.io/issues/4522580880/?referrer=github_integration)
Use `keepAlive` for all fetch requests
- Replace all node-fetch `fetch` requests by the custom `fetchWithKeelAlive` helper function
=> fix: use keep alive for remaining fetch requests

src/helpers/limits.ts
Full context: https://discord.com/channels/955773041898573854/1221106380300357804/1228248728964431932
Limit for normal space on testent will be the same as verified
- Try creating proposals on testnet, new limit will be `20` per day and `100` per month
=> fix: Update testnet space limit to be same as verified spaces

src/helpers/actions.ts, src/writer/delete-proposal.ts
Fix issue with #127 , where the storing of leaderboard data is failing due to failing query, using data from 2 tables with different encoding, resulting in following error
```
warn: [ingestor] msg validation failed (typed data): {"cause":{"code":"ER_CANT_AGGREGATE_2COLLATIONS","errno":1267,"sqlMessage":"Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='","sqlState":"HY000","index":0,"sql":"\n      INSERT INTO leaderboard (vote_count, user, space)\n        (SELECT * FROM (\n          SELECT COUNT(votes.id) AS vote_count, voter, space\n          FROM votes\n          JOIN spaces ON spaces.id = votes.space\n          WHERE spaces.deleted = 0 AND space IN ('coinside01.eth')\n          GROUP BY voter, space\n        ) AS t)\n      ON …
```
=> fix: fix invalid `JOIN` queries due to different collation

src/ingestor.ts
While voting If `choice` is a string but if it contains an error we are not returning any error, and it is confusing for some users
- Send a vote with invalid json in `choice`, here is an example curl:
```bash
curl --location 'http://localhost:3001' \
--header 'Content-Type: application/json' \
--data '{
"sig": "0x",
"data": {
"types": {
"Vote": [
{
"name": "from",
"type": "address"
},
{
"name": "space",
"type": "string"
},
{
"name": "timestamp",
"type": "uint64"
},
{
"name": "proposal",
"type": "bytes32"
},
{
"name": "choice",
"type": "string"
},
{
"name": "reason",
"type": "string"
},
{
"name": "app",
"type": "string"
},
{
"name": "metadata",
"type": "string"
}
]
},
"domain": {
"name": "snapshot",
"version": "0.1.4"
},
"message": {
"app": "snapshot",
"from": …
```
=> fix: Throw error if choice is invalid

src/writer/delete-proposal.ts
Fix https://snapshot-labs.sentry.io/issues/4542214149/events/044eed1cb2954dd5a772a29ac1b23eeb/?project=4505606761152512&query=is%3Aunresolved&referrer=previous-event&statsPeriod=90d&stream_index=5
Fix MySQL error where the `proposal_count` was set to a negative number.
As SQL transactions are not used, we can not guarantee that all counters are up-to-date
=> fix: prevent negative leaderboard counters

scripts/refresh_leaderboard_counters.ts
This PR refactor the leaderboard refresh script to accept an additional `pivot` argument, to restart the script from a specific `created` timestamp
Script now takes 2 optional arguments:
- `--space ID` : to filter by specific space ID (useful for migration)
- `--pivot TS` : to filter the spaces by `created`, and will target only spaces >= TS, useful to resume script at a specific point, when running on whole database.
=> fix: add params to restart leaderboard refresh script from arbitrary point

src/helpers/moderation.ts, test/integration/helpers/moderation.test.ts
- [ Handle special chars ](https://discord.com/channels/955773041898573854/1221106380300357804/1237318479829405716) eg: `clcula` is matching if flaggedLinks contains `clc.la`
- Detect even if the protocol is either `http` or `https` or no protocol at all
- Detect if the link contains a subdomain, for example using `www`
- Detect if the path is anything else than flagged one
- Detect if the link is case-insensitive
- Run `yarn test:integration` which contains all the new cases
=> fix: Flagged link check to handle special chars

scripts/refresh_leaderboard_counters.ts, src/helpers/actions.ts
This PR improves the refresh leaderboard script
- Instead of batching the requests by spaces, it is now batched by voter, resulting in much smaller query, but with whole script taking longer due to huge number of voters
- the `pivot` arg is now about the votes created date, and not space
- Split the refresh proposals and votes into 2 actions
Refresh the proposals count with 
```
yarn ts-node scripts/refresh_leaderboard_counters.ts --type proposal
```
Refresh the votes count with 
```
yarn ts-node scripts/refresh_leaderboard_counters.ts --type vote
```
Both can be filtered by `--space` and vote have additional `pivot` (vote date)
=> refactor: improve refresh leaderboard script

src/helpers/actions.ts, src/writer/follow.ts, test/fixtures/space.ts, test/integration/helpers/actions.test.ts, test/integration/writer/proposal.test.ts
This PR uses a whitelist to validate the `network` argument, and will check for sx space only if it's a valid SX network, compared to before, where it would consider all non-default-network as SX network.
This PR will fix an issue where people are still trying to pass the `network` params when creating a proposal
=> fix: use whitelist to validate space network

scripts/init_leaderboard_counters.ts
The current refresh_leaderboard_counter script is too slow to refresh counters for the whole database. It will be kept and still used for task such as space deletion and migration, but another script will be necessary for the counter initialization
Create another script to initialize leaderboard votes counter
- Get voters per day, and one day at a time until pivot === today
- Do not use `JOIN` query, for faster query
- Process one user/space at a time
There's still a `group by` in the query, that can be moved to nodejs in case the query is not performant enough
- Run `yarn ts-node scripts/init_leaderboard_counters.ts`
- It should populate the `vote_count` and `last_vote` in the leaderboard tables
=> fix: Add script to initialize leaderboard counters

scripts/init_leaderboard_counters.ts
Fix init leaderboard script not processing all days after pivot correctly
=> fix: fix init script not processing all days after pivot

src/writer/follow.ts
Following https://github.com/snapshot-labs/sx-monorepo/pull/327 
Remove goerli from supported follows network
=> fix: remove deprecated goerli network from follows network

src/writer/vote.ts
Following this https://github.com/snapshot-labs/snapshot-sequencer/pull/359
Ignore 504 errors from missed validation
=> fix: ignore 504 errors from score-api

src/helpers/utils.ts
This PR is to enable vote overriding for `split-delegation` strategy https://github.com/snapshot-labs/snapshot-strategies/pull/1484 If `delegationOverride` is `true`
- Create a proposal by enabling `split-delegation` strategy on your space with `delegationOverride` param as `true`
- User should be able to override their vote
=> fix: Check for split-delegation strategy with delegationOverride

src/helpers/actions.ts, test/integration/helpers/actions.test.ts
The SX API we're currently using to check and validate onchain spaces on Follow actions is only for a single type of network
Fix #355 
Use correct SX API, for each different network types
- Use a list of different SX API, for each network, like on stamp https://github.com/snapshot-labs/stamp/blob/master/src/resolvers/space-sx.ts
- Run `yarn test`
=> fix: use correct SX API for different network

src/helpers/actions.ts, test/integration/helpers/actions.test.ts
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/448
This PR enforce that:
- Space ID is always lower case on space creation
- Checking for space existence is case insensitive, so `a.eth` and `A.eth` are equal (this is already the case with the current table collation, will be more useful once we moved to the new case sensitive collation)
=> fix: enforce lowercase space ID

src/helpers/actions.ts, src/helpers/utils.ts, src/writer/profile.ts, src/writer/settings.ts, test/unit/writer/profile.test.ts
Related to https://discord.com/channels/955773041898573854/1031838169282392144/1249097030094291066
This PR will call stamp service and clear the relevant cache on avatar update
Cache will be cleared when updating:
- user's avatar
- spaces' avatar
=> feat: clear stamp cache on data update

src/writer/statement.ts
When trying to create a new statement, the query is failing with `ER_NO_DEFAULT_FOR_FIELD ` error, due to the `updated` field not having a default value
This PR set a default value when inserting a new statement
=> fix: fix missing value for updated column

test/schema.sql
Change the length of the `id` field in statements to be the same as other tables
=> fix: Increase statements id length

src/helpers/actions.ts, src/helpers/utils.ts, src/writer/follow.ts, src/writer/statement.ts, src/writer/unfollow.ts, test/integration/helpers/actions.test.ts, test/schema.sql
Related to https://github.com/snapshot-labs/sx-monorepo/pull/407
This PR:
- add support for the new Statement `discourse`, `network` and `status` properties.
- update database schema, for the new columns and index (have to update schema manually before merge)
=> feat: support new statement properties

scripts/refresh-space-leaderboard.ts, scripts/refresh_spaces_counters.ts
Related to https://github.com/snapshot-labs/snapshot-sequencer/pull/406
Context: DIscussed on discord
=> fix: update refresh spaces counters script

src/ingestor.ts, test/integration/ingestor.test.ts
Reopening same PR as #417 
But with an additional fix to validate space ID only for offchain spaces
- See #417 
- With this PR fix, we check space ID only if it's an ID sent by v1 (without network prefix), or if it's an offchain ID sent by v2 (with `s:` prefix)
=> fix: validate space ID (bis)

src/helpers/actions.ts
We migrated to .box domain, currently old domain no longer works so sequencer fails as well.
=> fix: update starknet API urls

src/writer/profile.ts, test/unit/writer/profile.test.ts
This PR fix the issue where the stamp cache refresh was not triggered on profile name update, due to monitoring on wrong field name
=> fix: fix stamp cache refresh on profile name update not triggering

test/integration/writer/profile.test.ts, test/unit/writer/profile.test.ts
Fix tests from #437 
Tests have been fixed incorrectly in #437, this PR fix that. There should be only 1 call to `clearStampCache`
Also move the test to integration, since they depends on a database, and are not unit test
=> chore: fix tests

src/ingestor.ts, src/writer/proposal.ts, src/writer/update-proposal.ts, test/schema.sql
Towards https://github.com/snapshot-labs/workflow/issues/143
- Accepts labels on proposals
- Run the SQL query to create new row (labels)
- Use https://github.com/snapshot-labs/sx-monorepo/pull/838 and use local sequencer and hub
- Create a proposal with labels
```SQL
ALTER TABLE proposals
ADD COLUMN labels JSON DEFAULT NULL AFTER choices;
```
=> feat: Labels on proposal

src/writer/statement.ts
This PR removes the `source` property on statement update
=> fix: remove statement source on statement update

src/helpers/actions.ts, src/helpers/poke.ts
Fixes https://github.com/snapshot-labs/workflow/issues/253
- In `src/helpers/poke.ts` comment the code that checks validation: (until we merge https://github.com/snapshot-labs/snapshot.js/pull/1074)
```ts
// if (snapshot.utils.validateSchema(snapshot.schemas.space, space) !== true) {
//   return Promise.reject('invalid space format');
// }
```
- Open http://localhost:3001/spaces/cow.eth/poke
- Should save space settings without any error (domain should be saved as `vote.cow.fi`)
- In `src/helpers/actions.ts` add `delete settings.domain` on line `10`
- Open http://localhost:3001/spaces/cowtesting.eth/poke 
- Should save space settings without any error
=> fix: Remove https from domain and default delegationNetwork to mainnet

src/ingestor.ts
On testnet.snapshot.org we are not allowing signs from sepolia safe to update space settings, we only allow eth mainnet right now
- Allows signatures from sepolia safes on testnet.snapshot.org and mainnet on snapshot.org
- Go to your space settings on testnet 
- Update settings with a Sepolia safe
- Before fix, it should not allow
- After fix, It should allow
- It should still allow signs from mainnet on prod
=> fix: Allow signatures from sepolia safes on testnet

src/ingestor.ts, src/writer/proposal.ts, src/writer/update-proposal.ts
Towards https://github.com/snapshot-labs/workflow/issues/277
- Accept privacy field if space's privacy is `any`
- Else use space's privacy as default value
- Reject if proposal has `privacy` and space is not using 'any'
- ~~Once a new version is created with https://github.com/snapshot-labs/snapshot.js/pull/1082~~
- Change your space settings to `any` (using UI here https://github.com/snapshot-labs/sx-monorepo/pull/954)
- Send a proposal with both `""` and `"shutter"` values in privacy
=> feat: privacy field in proposal data

src/ingestor.ts
- Allows messages that are signed before 5 days time period (before it was 3 days)
=> fix: Increase timestamp check to 5 days

src/writer/follow.ts, test/integration/writer/follows.test.ts
Following on https://github.com/snapshot-labs/snapshot-sequencer/pull/401#issuecomment-2210284601
This PR fix an edge case when checking the limit of followed spaces, when a followed space has been deleted, but will still be counted toward the limit.
This PR will ignore deleted spaces from the limit count
=> fix: ignore deleted spaces when checking for followed spaces limit

src/writer/settings.ts, test/unit/writer/settings.test.ts
Toward https://github.com/snapshot-labs/workflow/issues/362
See sister PR for sx UI https://github.com/snapshot-labs/sx-monorepo/pull/1087
Custom domain and skins will also be disabled from v1 UI with https://github.com/snapshot-labs/snapshot-v1/pull/4960
This PR will accepts a space settings update with custom domain only if:
- it's a turbo space
- the space has previously setup a custom domain
=> feat: enable domain edition only on turbo and legacy spaces

test/schema.sql
This PR adds the missing `options` table from schema.sql file
=> fix: add options table to schema.sql

scripts/import-skins.ts, test/schema.sql
Toward https://github.com/snapshot-labs/workflow/issues/275
This PR adds a script to import skins from the snapshot-spaces repository into the new `skins` table.
Only skins used by the v2 (skins used by turbo spaces, and spaces with existing custom domains) will be imported
Create the table with
```
CREATE TABLE skins (
id VARCHAR(100) NOT NULL,
bg_color VARCHAR(6) DEFAULT NULL,
link_color VARCHAR(6) DEFAULT NULL,
text_color VARCHAR(6) DEFAULT NULL,
content_color VARCHAR(6) DEFAULT NULL,
border_color VARCHAR(6) DEFAULT NULL,
heading_color VARCHAR(6) DEFAULT NULL,
primary_color VARCHAR(6) DEFAULT NULL,
header_color VARCHAR(6) DEFAULT NULL,
PRIMARY KEY (id)
);
```
=> feat: add script to import skins

src/ingestor.ts
https://github.com/snapshot-labs/sx-monorepo/pull/1218#discussion_r1971371127
This is to allow only mainnet Safes to delete spaces, similar to `settings` action
=> fix:  `delete-space` action should use default network instead of space network

src/api.ts
- Will be helpful to debug
Sometimes logs are not printed if error is not a object,
Try passing `plugins: ""` while proposal creation,
Before:
```bash
warn: [ingestor] msg validation failed (typed data): {}
```
After
```bash
warn: [ingestor] msg validation failed (typed data): Unexpected end of JSON input
```
=> chore: log unhandled errors

src/ingestor.ts
Whilte creating proposals, Our docs suggest that we need to pass `plugins`  as object in string
```js
plugins:  JSON.stringify({})
```
but many times users send a empty string or empty object for `plugins`
```js
plugins:  ''
```
```js
plugins:  {}
```
This fix will accept both and fallback to `{}`
=> fix: accept empty string/object in plugins

src/writer/proposal.ts
Towards https://github.com/snapshot-labs/workflow/issues/487
- Allow copeland on production
- Just trust me bro
- or Send a payload with copeland method on prod
=> fix: allow copeland on production

src/helpers/actions.ts, src/writer/proposal.ts, test/integration/ingestor.test.ts, test/schema.sql, test/unit/writer/proposal.test.ts, test/unit/writer/settings.test.ts
Closes https://github.com/snapshot-labs/workflow/issues/497
Stops proposal creation for spaces using non-premium network (main network, network inside strategy or inside multichain strategy)
- Try changing the settings of space to use a non-premium network
- Create a proposal on v1
- It should throw any error
=> fix: prevent non-premium networks

src/writer/proposal.ts, test/unit/writer/proposal.test.ts
Right now we are not allowing turbo spaces to create proposals with non-premium networks
- Create  proposal with turbo space
=> fix: allow turbo spaces to create proposals with non-premium networks

src/helpers/poke.ts
Use pineapple gateway on poke
- Attach a network listner
- try going to http://localhost:3001/spaces/testsnapshotspace.eth/poke
- you should see the request is sent to pineapple instead of ipfs.snapshot.box
=> chore: use pineapple gateway to get JSON on poke

src/api.ts, src/scores.ts
This PR fix the issue where a last minute vote just before proposal closing is not taken into account when computing the proposal final score, due to concurrency issue
=> feat: add delay before finalizing proposal scores

src/helpers/alias.ts, src/helpers/shutter.ts, src/ingestor.ts, test/fixtures/alias.ts, test/integration/helpers/alias.test.ts, test/unit/helpers/alias.test.ts
Toward https://github.com/snapshot-labs/workflow/issues/562
This PR allows aliases from starknet address to submit votes and create/delete proposals
- Add a whitelist voting strategy to your space, with your starknet address
- Create an alias with your starknet address
- Using the SDK, submit a vote with that alias/create a proposal with that alias (set the `from` to your starknet address)
Depends on https://github.com/snapshot-labs/snapshot.js/pull/1152
=> feat: allow vote and proposal handling from starknet aliases

src/helpers/mysql.ts
Applied a single call to `bluebird.promisifyAll([Pool, Connection])` at the top of mysql.ts so it executes before any pools are created
=> fix: remove duplicate promisification of Pool and Connection in mysql helper

src/helpers/alias.ts
Following https://github.com/snapshot-labs/snapshot.js/pull/1164
This PR will allow starknet aliases to flag proposals, when it's a space admin or moderator
=> feat: allow starknet aliases to flag proposals

src/helpers/utils.ts
Add `split-delegation` to the list of overriding strategies
=> fix: add split-delegation to list of override strategies

src/writer/settings.ts, test/unit/writer/settings.test.ts
Related to https://github.com/snapshot-labs/workflow/issues/605
This PR adds validation to prevent spaces from creating circular references in the space hierarchy by setting themselves as their own parent or including themselves in their children array.
- All existing tests continue to pass
- New tests validate both rejection and acceptance scenarios
=> feat: prevent spaces from setting themselves as parent or child

package.json, src/constants.ts, src/helpers/entityValue.ts, src/helpers/proposalsScoresValue.ts, src/index.ts, src/scores.ts, yarn.lock
In continuation of https://github.com/snapshot-labs/snapshot-sequencer/pull/593
This PR will set the proposal's scores_total_value with an async script
It's using a simple local computation, to get the total value, from existing data, only on closed proposals, and with final scores_state.
=> feat(overlord): compute proposal's `scores_total_value`
